apiVersion: v1
kind: Service
metadata:
  labels:
    component: enterprise-gateway
  name: enterprise-gateway
spec:
  # clusterIP: 10.233.0.53
  # clusterIPs:
  # - 10.233.0.53
  # internalTrafficPolicy: Cluster
  # ipFamilies:
  # - IPv4
  # ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: http-response
    port: 8877
    protocol: TCP
    targetPort: 8877
  selector:
    gateway-selector: enterprise-gateway
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  type: ClusterIP
