apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    component: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jupyter
  template:
    metadata:
      labels:
        component: jupyter
    spec:
      serviceAccountName: hub
      containers:
        - name: hub
          # image: kienmn97/jupyter-hub:1.1.0
          image: jupyterhub/k8s-hub:3.0.0-0.dev.git.6143.h246f1f0c
          imagePullPolicy: Always
          command: ["jupyterhub", "--config", "/usr/local/etc/jupyterhub/jupyterhub_config.py","--upgrade-db"]
          ports:
            - containerPort: 8081
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              value: d360afa4a67ecb9aa93d1ad77df44edcfde6ef211eaf6a2da77367d3ec7f1665
            - name: COOKIE_SECRET
              value: 5deedeade118498ba6882b88de301277038a4f3d41d01f3975438cd34c69c698
          volumeMounts:
            - mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.py
              subPath: jupyterhub_config.py
              name: config
            - mountPath: /usr/local/etc/jupyterhub/z2jh.py
              name: config
              subPath: z2jh.py
            - mountPath: /usr/local/etc/jupyterhub/config/
              name: config
            # - mountPath: /usr/local/etc/jupyterhub/secret/
            #   name: secret
            - mountPath: /srv/jupyterhub
              name: hub-db-dir
          # resources:
          #   requests:
          #     cpu: 100m
      securityContext:
        fsGroup: 0
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: hub
        #- name: config
        #  configMap:
        #    name: hub-config
        # - name: secret
        #   secret:
        #     secretName: hub-secret
        - name: hub-db-dir
          persistentVolumeClaim:
            claimName: hub-db-dir
