apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hub-db-dir
  labels:
    component: hub
spec:
  storageClassName: cinder-csi-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi