apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: proxy
  strategy:
    type: Recreate
  #  {{- .Values.proxy.deploymentStrategy | toYaml | trimSuffix "\n" | nindent 4 }}
  template:
    metadata:
      labels:
        app: jupyterhub
        component: proxy
        release: jupyterhub
  #      {{- /* Changes here will cause the Deployment to restart the pods. */}}
  #      {{- include "jupyterhub.matchLabels" . | nindent 8 }}
        hub.jupyter.org/network-access-hub: "true"
        hub.jupyter.org/network-access-singleuser: "true"
  #      {{- if .Values.proxy.labels }}
  #      {{- .Values.proxy.labels | toYaml | trimSuffix "\n" | nindent 8 }}
  #      {{- end }}
  #    annotations:
        # This lets us autorestart when the secret changes!
  #      checksum/hub-secret: {{ include (print $.Template.BasePath "/hub/secret.yaml") . | sha256sum }}
  #      checksum/proxy-secret: {{ include (print $.Template.BasePath "/proxy/secret.yaml") . | sha256sum }}
  #      {{- if .Values.proxy.annotations }}
  #      {{- .Values.proxy.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
  #      {{- end }}
    spec:
      containers:
        - name: chp
          image: jupyterhub/configurable-http-proxy:4.5.3
          command:
            - configurable-http-proxy
            - --ip=
            - --api-ip=
            - --api-port=8001
            - --default-target=http://hub:$(HUB_SERVICE_PORT)
            - --error-target=http://hub:$(HUB_SERVICE_PORT)/hub/error
            - --port=8000
            - --log-level=debug
          # resources:
          #   {{- .Values.proxy.chp.resources | toYaml | trimSuffix "\n" | nindent 12 }}
          securityContext:
            # Don't allow any process to execute as root inside the container
            allowPrivilegeEscalation: false
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              value: d360afa4a67ecb9aa93d1ad77df44edcfde6ef211eaf6a2da77367d3ec7f1665
          # {{- with .Values.proxy.chp.image.pullPolicy }}
          # imagePullPolicy: {{ . }}
          # {{- end }}
          ports:
            - containerPort: 8000
              name: proxy-public
            - containerPort: 8001
              name: api