apiVersion: v1
kind: Service
metadata:
  labels:
    component: proxy
  name: proxy-api
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    component: proxy
  type: ClusterIP
