apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    component: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jupyter
  template:
    metadata:
      labels:
        component: jupyter
    spec:
      serviceAccountName: hub
      containers:
        - name: hub
          image: jupyterhub/k8s-hub:2.0.0
          imagePullPolicy: Always
          command: ["jupyterhub", "--config", "/usr/local/etc/jupyterhub/jupyterhub_config.py","--upgrade-db"]
          ports:
            - containerPort: 8081
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              value: AUTH_TOKEN 
            - name: COOKIE_SECRET
              value: SECRET
          volumeMounts:
            - mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.py
              subPath: jupyterhub_config.py
              name: config
            - mountPath: /usr/local/etc/jupyterhub/z2jh.py
              name: config
              subPath: z2jh.py
            - mountPath: /usr/local/etc/jupyterhub/config/
              name: config
            - mountPath: /srv/jupyterhub
              name: hub-db-dir
      securityContext:
        fsGroup: 0
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: hub
        - name: hub-db-dir
          persistentVolumeClaim:
            claimName: hub-db-dir
