apiVersion: v1
kind: PersistentVolume
metadata:
  # annotations:
  #   pv.kubernetes.io/provisioned-by: cinder.csi.openstack.org
  # finalizers:
  # - kubernetes.io/pv-protection
  # - external-attacher/cinder-csi-openstack-org
  name: pv-csi-dummy
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: hub-db-dir
  csi:
    driver: cinder.csi.openstack.org
    fsType: ext4
    # volumeAttributes:
    #   storage.kubernetes.io/csiProvisionerIdentity: 1678702426982-8081-cinder.csi.openstack.org
    volumeHandle: 314a0f36-d365-41ed-9307-b9fcd670510e
  persistentVolumeReclaimPolicy: Delete
  storageClassName: cinder-csi
  volumeMode: Filesystem