apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-container
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: HOSTNAME
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
            - name: BROKER_ID_COMMAND
              value: "echo $(HOSTNAME) | awk -F'-' '{print $2}'"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zk-cs.kafka.svc.cluster.local:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(HOST_IP):30092"
            - name: KAFKA_ADVERTISED_PORT
              value: "30092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_PORT
              value: "9092"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_BACKEND_URL
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: kafkadir
              mountPath: /mnt/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafkadir
      spec:
        storageClassName: cinder-csi-2
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi