apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
    component: kafka
  name: kafka-service
spec:
  type: NodePort
  ports:
    - name: 'broker'
      protocol: TCP
      port: 9092
      nodePort: 30092
      targetPort: 9092
  selector:
    app: kafka
    component: kafka